### ISSUE TITLE
Mention the Extended Euclidean Algorithm to compute modular multiplicative inverse

### ISSUE THREAD

**Issue by KasparEtter** [teachbitcoin/teachbitcoin.github.io#2]
You write on https://teachbitcoin.github.io/ec_math.html#/7:
> Division over 𝔽p can only be performed by maintaining a multiplication table for all pairs of 𝔽p.

I have never heard of multiplication tables before. As far as I know, the standard way to compute the modular multiplicative inverse is with the [Extended Euclidean Algorithm](https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm). While your trick with Fermat's little theorem on https://teachbitcoin.github.io/ec_math.html#/8 is neat, I doubt it's faster than the Extended Euclidean Algorithm (for prime fields) but I would have to verify this. In any case, my objection is not to slide 9 (according to the number in the bottom right corner) but to the formulation on slide 8.

**Comment by KasparEtter** [comment]
I found what I had been looking for (https://en.wikipedia.org/wiki/Modular_multiplicative_inverse#Computation):
> In big O notation, the Extended Euclidean algorithm runs in time O(log(m)2), assuming |a| < m, and is considered to be very fast and generally more efficient than its alternative, exponentiation.

**Comment by jachiang** [comment]
I need to read up on the ext euclidian algorithm this week and happy to update it later in the material. Might even have some follow up questions to post here.

**Comment by KasparEtter** [comment]
Personally, I think it's enough to just mention that an efficient algorithm exists and that it's called Extended Euclidean algorithm. 🙂

**Comment by jachiang** [comment]
I have fixed the page per your suggestions:
file:///Users/jamesc/Dropbox/repos/04-libbitcoin/teachbitcoin.github.io/ec_math.html#/7 

Thanks again.
